# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}: {
  "@better-auth/core@1.5.2" = fetchurl {
    url = "https://registry.npmjs.org/@better-auth/core/-/core-1.5.2.tgz";
    hash = "sha512-svaKRVN/p3+g++kljLEedHC+RgDlGsVr87tKiATr5xIE7xqLO1If906pMTNMfhF08N5r7pMbix/mRYdObuPKHA==";
  };
  "@better-auth/drizzle-adapter@1.5.2" = fetchurl {
    url = "https://registry.npmjs.org/@better-auth/drizzle-adapter/-/drizzle-adapter-1.5.2.tgz";
    hash = "sha512-29e7UCwqTriIuDdEr1xbSx4qGg6Ag3aTopzRavPyOCYJyzTwePw8iZ9zaJF1fsLmLeany7LW069NMDf6+3tz/w==";
  };
  "@better-auth/kysely-adapter@1.5.2" = fetchurl {
    url = "https://registry.npmjs.org/@better-auth/kysely-adapter/-/kysely-adapter-1.5.2.tgz";
    hash = "sha512-PaP+KPJ6Cw0DxzuZLH6eR0oFhS5Iq/KjYvmZt76fCl5Q7Ys9Cct0kXVVlrD1bftiznTpV+UKMfwjcCWvtc1l4w==";
  };
  "@better-auth/memory-adapter@1.5.2" = fetchurl {
    url = "https://registry.npmjs.org/@better-auth/memory-adapter/-/memory-adapter-1.5.2.tgz";
    hash = "sha512-vCbmMpUAisISRVxzNFIxkvO3wm63fzwSxAOO9Xktl77VyEyh8zliBNcW8S6+9DOeolVRKhjWEg7UaBOtIhFX/Q==";
  };
  "@better-auth/mongo-adapter@1.5.2" = fetchurl {
    url = "https://registry.npmjs.org/@better-auth/mongo-adapter/-/mongo-adapter-1.5.2.tgz";
    hash = "sha512-fJd+Z7fgRFgK2W7oxbFYM9K10yEUs/hlALzihCdDgSyRg9XFLBMJkMcECRqBsop/cZUjwZxLBTQPsIpgx9ix1g==";
  };
  "@better-auth/prisma-adapter@1.5.2" = fetchurl {
    url = "https://registry.npmjs.org/@better-auth/prisma-adapter/-/prisma-adapter-1.5.2.tgz";
    hash = "sha512-9GB4q91Q16wSSsi1vFP/RZNW0GNmdxTiDcE2MX1fC4Hlmo6UuT4WRv+94YPYs3/tPhsJ17k5Lt+rKTOK8S6Kbw==";
  };
  "@better-auth/telemetry@1.5.2" = fetchurl {
    url = "https://registry.npmjs.org/@better-auth/telemetry/-/telemetry-1.5.2.tgz";
    hash = "sha512-Cukyj5yciFNGtx5SkQCop2wOjpHuq2ZHL3V7ydVFe51WUNCXd+v1Sbed2sIfT/8hOcSB+NefALXNv1yTSxKkAQ==";
  };
  "@better-auth/utils@0.3.1" = fetchurl {
    url = "https://registry.npmjs.org/@better-auth/utils/-/utils-0.3.1.tgz";
    hash = "sha512-+CGp4UmZSUrHHnpHhLPYu6cV+wSUSvVbZbNykxhUDocpVNTo9uFFxw/NqJlh1iC4wQ9HKKWGCKuZ5wUgS0v6Kg==";
  };
  "@better-fetch/fetch@1.1.21" = fetchurl {
    url = "https://registry.npmjs.org/@better-fetch/fetch/-/fetch-1.1.21.tgz";
    hash = "sha512-/ImESw0sskqlVR94jB+5+Pxjf+xBwDZF/N5+y2/q4EqD7IARUTSpPfIo8uf39SYpCxyOCtbyYpUrZ3F/k0zT4A==";
  };
  "@chevrotain/cst-dts-gen@10.5.0" = fetchurl {
    url = "https://registry.npmjs.org/@chevrotain/cst-dts-gen/-/cst-dts-gen-10.5.0.tgz";
    hash = "sha512-lhmC/FyqQ2o7pGK4Om+hzuDrm9rhFYIJ/AXoQBeongmn870Xeb0L6oGEiuR8nohFNL5sMaQEJWCxr1oIVIVXrw==";
  };
  "@chevrotain/gast@10.5.0" = fetchurl {
    url = "https://registry.npmjs.org/@chevrotain/gast/-/gast-10.5.0.tgz";
    hash = "sha512-pXdMJ9XeDAbgOWKuD1Fldz4ieCs6+nLNmyVhe2gZVqoO7v8HXuHYs5OV2EzUtbuai37TlOAQHrTDvxMnvMJz3A==";
  };
  "@chevrotain/types@10.5.0" = fetchurl {
    url = "https://registry.npmjs.org/@chevrotain/types/-/types-10.5.0.tgz";
    hash = "sha512-f1MAia0x/pAVPWH/T73BJVyO2XU5tI4/iE7cnxb7tqdNTNhQI3Uq3XkqcoteTmD4t1aM0LbHCJOhgIDn07kl2A==";
  };
  "@chevrotain/utils@10.5.0" = fetchurl {
    url = "https://registry.npmjs.org/@chevrotain/utils/-/utils-10.5.0.tgz";
    hash = "sha512-hBzuU5+JjB2cqNZyszkDHZgOSrUUT8V3dhgRl8Q9Gp6dAj/H5+KILGjbhDpc3Iy9qmqlm/akuOI2ut9VUtzJxQ==";
  };
  "@electric-sql/pglite-socket@0.0.20" = fetchurl {
    url = "https://registry.npmjs.org/@electric-sql/pglite-socket/-/pglite-socket-0.0.20.tgz";
    hash = "sha512-J5nLGsicnD9wJHnno9r+DGxfcZWh+YJMCe0q/aCgtG6XOm9Z7fKeite8IZSNXgZeGltSigM9U/vAWZQWdgcSFg==";
  };
  "@electric-sql/pglite-tools@0.2.20" = fetchurl {
    url = "https://registry.npmjs.org/@electric-sql/pglite-tools/-/pglite-tools-0.2.20.tgz";
    hash = "sha512-BK50ZnYa3IG7ztXhtgYf0Q7zijV32Iw1cYS8C+ThdQlwx12V5VZ9KRJ42y82Hyb4PkTxZQklVQA9JHyUlex33A==";
  };
  "@electric-sql/pglite@0.3.15" = fetchurl {
    url = "https://registry.npmjs.org/@electric-sql/pglite/-/pglite-0.3.15.tgz";
    hash = "sha512-Cj++n1Mekf9ETfdc16TlDi+cDDQF0W7EcbyRHYOAeZdsAe8M/FJg18itDTSwyHfar2WIezawM9o0EKaRGVKygQ==";
  };
  "@hono/node-server@1.19.9" = fetchurl {
    url = "https://registry.npmjs.org/@hono/node-server/-/node-server-1.19.9.tgz";
    hash = "sha512-vHL6w3ecZsky+8P5MD+eFfaGTyCeOHUIFYMGpQGbrBTSmNNoxv0if69rEZ5giu36weC5saFuznL411gRX7bJDw==";
  };
  "@mongodb-js/saslprep@1.4.6" = fetchurl {
    url = "https://registry.npmjs.org/@mongodb-js/saslprep/-/saslprep-1.4.6.tgz";
    hash = "sha512-y+x3H1xBZd38n10NZF/rEBlvDOOMQ6LKUTHqr8R9VkJ+mmQOYtJFxIlkkK8fZrtOiL6VixbOBWMbZGBdal3Z1g==";
  };
  "@mrleebo/prisma-ast@0.13.1" = fetchurl {
    url = "https://registry.npmjs.org/@mrleebo/prisma-ast/-/prisma-ast-0.13.1.tgz";
    hash = "sha512-XyroGQXcHrZdvmrGJvsA9KNeOOgGMg1Vg9OlheUsBOSKznLMDl+YChxbkboRHvtFYJEMRYmlV3uoo/njCw05iw==";
  };
  "@noble/ciphers@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@noble/ciphers/-/ciphers-2.1.1.tgz";
    hash = "sha512-bysYuiVfhxNJuldNXlFEitTVdNnYUc+XNJZd7Qm2a5j1vZHgY+fazadNFWFaMK/2vye0JVlxV3gHmC0WDfAOQw==";
  };
  "@noble/hashes@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@noble/hashes/-/hashes-2.0.1.tgz";
    hash = "sha512-XlOlEbQcE9fmuXxrVTXCTlG2nlRXa9Rj3rr5Ue/+tX+nmkgbX720YHh0VR3hBF9xDvwnb8D2shVGOwNx+ulArw==";
  };
  "@prisma/client-runtime-utils@7.4.2" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/client-runtime-utils/-/client-runtime-utils-7.4.2.tgz";
    hash = "sha512-cID+rzOEb38VyMsx5LwJMEY4NGIrWCNpKu/0ImbeooQ2Px7TI+kOt7cm0NelxUzF2V41UVVXAmYjANZQtCu1/Q==";
  };
  "@prisma/client@7.4.2" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/client/-/client-7.4.2.tgz";
    hash = "sha512-ts2mu+cQHriAhSxngO3StcYubBGTWDtu/4juZhXCUKOwgh26l+s4KD3vT2kMUzFyrYnll9u/3qWrtzRv9CGWzA==";
  };
  "@prisma/config@7.4.2" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/config/-/config-7.4.2.tgz";
    hash = "sha512-CftBjWxav99lzY1Z4oDgomdb1gh9BJFAOmWF6P2v1xRfXqQb56DfBub+QKcERRdNoAzCb3HXy3Zii8Vb4AsXhg==";
  };
  "@prisma/debug@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/debug/-/debug-7.2.0.tgz";
    hash = "sha512-YSGTiSlBAVJPzX4ONZmMotL+ozJwQjRmZweQNIq/ER0tQJKJynNkRB3kyvt37eOfsbMCXk3gnLF6J9OJ4QWftw==";
  };
  "@prisma/debug@7.4.2" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/debug/-/debug-7.4.2.tgz";
    hash = "sha512-aP7qzu+g/JnbF6U69LMwHoUkELiserKmWsE2shYuEpNUJ4GrtxBCvZwCyCBHFSH2kLTF2l1goBlBh4wuvRq62w==";
  };
  "@prisma/dev@0.20.0" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/dev/-/dev-0.20.0.tgz";
    hash = "sha512-ovlBYwWor0OzG+yH4J3Ot+AneD818BttLA+Ii7wjbcLHUrnC4tbUPVGyNd3c/+71KETPKZfjhkTSpdS15dmXNQ==";
  };
  "@prisma/engines-version@7.5.0-10.94a226be1cf2967af2541cca5529f0f7ba866919" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/engines-version/-/engines-version-7.5.0-10.94a226be1cf2967af2541cca5529f0f7ba866919.tgz";
    hash = "sha512-5FIKY3KoYQlBuZC2yc16EXfVRQ8HY+fLqgxkYfWCtKhRb3ajCRzP/rPeoSx11+NueJDANdh4hjY36mdmrTcGSg==";
  };
  "@prisma/engines@7.4.2" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/engines/-/engines-7.4.2.tgz";
    hash = "sha512-B+ZZhI4rXlzjVqRw/93AothEKOU5/x4oVyJFGo9RpHPnBwaPwk4Pi0Q4iGXipKxeXPs/dqljgNBjK0m8nocOJA==";
  };
  "@prisma/fetch-engine@7.4.2" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/fetch-engine/-/fetch-engine-7.4.2.tgz";
    hash = "sha512-f/c/MwYpdJO7taLETU8rahEstLeXfYgQGlz5fycG7Fbmva3iPdzGmjiSWHeSWIgNnlXnelUdCJqyZnFocurZuA==";
  };
  "@prisma/get-platform@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/get-platform/-/get-platform-7.2.0.tgz";
    hash = "sha512-k1V0l0Td1732EHpAfi2eySTezyllok9dXb6UQanajkJQzPUGi3vO2z7jdkz67SypFTdmbnyGYxvEvYZdZsMAVA==";
  };
  "@prisma/get-platform@7.4.2" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/get-platform/-/get-platform-7.4.2.tgz";
    hash = "sha512-UTnChXRwiauzl/8wT4hhe7Xmixja9WE28oCnGpBtRejaHhvekx5kudr3R4Y9mLSA0kqGnAMeyTiKwDVMjaEVsw==";
  };
  "@prisma/query-plan-executor@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/query-plan-executor/-/query-plan-executor-7.2.0.tgz";
    hash = "sha512-EOZmNzcV8uJ0mae3DhTsiHgoNCuu1J9mULQpGCh62zN3PxPTd+qI9tJvk5jOst8WHKQNwJWR3b39t0XvfBB0WQ==";
  };
  "@prisma/studio-core@0.13.1" = fetchurl {
    url = "https://registry.npmjs.org/@prisma/studio-core/-/studio-core-0.13.1.tgz";
    hash = "sha512-agdqaPEePRHcQ7CexEfkX1RvSH9uWDb6pXrZnhCRykhDFAV0/0P3d07WtfiY8hZWb7oRU4v+NkT4cGFHkQJIPg==";
  };
  "@standard-schema/spec@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@standard-schema/spec/-/spec-1.1.0.tgz";
    hash = "sha512-l2aFy5jALhniG5HgqrD6jXLi/rUWrKvqN/qJx6yoJsgKhblVd+iqqU4RCXavm/jPityDo5TCvKMnpjKnOriy0w==";
  };
  "@types/bun@1.3.10" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.10.tgz";
    hash = "sha512-0+rlrUrOrTSskibryHbvQkDOWRJwJZqZlxrUs1u4oOoTln8+WIXBPmAuCF35SWB2z4Zl3E84Nl/D0P7803nigQ==";
  };
  "@types/node@25.3.3" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.3.3.tgz";
    hash = "sha512-DpzbrH7wIcBaJibpKo9nnSQL0MTRdnWttGyE5haGwK86xgMOkFLp7vEyfQPGLOJh5wNYiJ3V9PmUMDhV9u8kkQ==";
  };
  "@types/pg@8.18.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/pg/-/pg-8.18.0.tgz";
    hash = "sha512-gT+oueVQkqnj6ajGJXblFR4iavIXWsGAFCk3dP4Kki5+a9R4NMt0JARdk6s8cUKcfUoqP5dAtDSLU8xYUTFV+Q==";
  };
  "@types/react@19.2.14" = fetchurl {
    url = "https://registry.npmjs.org/@types/react/-/react-19.2.14.tgz";
    hash = "sha512-ilcTH/UniCkMdtexkoCN0bI7pMcJDvmQFPvuPvmEaYA/NSfFTAgdUSLAoVjaRJm7+6PvcM+q1zYOwS4wTYMF9w==";
  };
  "@types/uuid@11.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/uuid/-/uuid-11.0.0.tgz";
    hash = "sha512-HVyk8nj2m+jcFRNazzqyVKiZezyhDKrGUA3jlEcg/nZ6Ms+qHwocba1Y/AaVaznJTAM9xpdFSh+ptbNrhOGvZA==";
  };
  "@types/webidl-conversions@7.0.3" = fetchurl {
    url = "https://registry.npmjs.org/@types/webidl-conversions/-/webidl-conversions-7.0.3.tgz";
    hash = "sha512-CiJJvcRtIgzadHCYXw7dqEnMNRjhGZlYK05Mj9OyktqV8uVT8fD2BFOB7S1uwBE3Kj2Z+4UyPmFw/Ixgw/LAlA==";
  };
  "@types/whatwg-url@13.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/whatwg-url/-/whatwg-url-13.0.0.tgz";
    hash = "sha512-N8WXpbE6Wgri7KUSvrmQcqrMllKZ9uxkYWMt+mCSGwNc0Hsw9VQTW7ApqI4XNrx6/SaM2QQJCzMPDEXE058s+Q==";
  };
  "aws-ssl-profiles@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/aws-ssl-profiles/-/aws-ssl-profiles-1.1.2.tgz";
    hash = "sha512-NZKeq9AfyQvEeNlN0zSYAaWrmBffJh3IELMZfRpJVWgrpEbtEpnjvzqBPf+mxoI287JohRDoa+/nsfqqiZmF6g==";
  };
  "better-auth@1.5.2" = fetchurl {
    url = "https://registry.npmjs.org/better-auth/-/better-auth-1.5.2.tgz";
    hash = "sha512-xEnt/RBsu/cjcN+IEsgeBqka/6QRaGzPFl5hnnJfZU/JxRGnDsVUDHXvJQRfecj8qA/1nPJOQjZ6qQL1Z7aN+Q==";
  };
  "better-call@1.3.2" = fetchurl {
    url = "https://registry.npmjs.org/better-call/-/better-call-1.3.2.tgz";
    hash = "sha512-4cZIfrerDsNTn3cm+MhLbUePN0gdwkhSXEuG7r/zuQ8c/H7iU0/jSK5TD3FW7U0MgKHce/8jGpPYNO4Ve+4NBw==";
  };
  "bson@7.2.0" = fetchurl {
    url = "https://registry.npmjs.org/bson/-/bson-7.2.0.tgz";
    hash = "sha512-YCEo7KjMlbNlyHhz7zAZNDpIpQbd+wOEHJYezv0nMYTn4x31eIUM2yomNNubclAt63dObUzKHWsBLJ9QcZNSnQ==";
  };
  "bun-types@1.3.10" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.10.tgz";
    hash = "sha512-tcpfCCl6XWo6nCVnpcVrxQ+9AYN1iqMIzgrSKYMB/fjLtV2eyAVEg7AxQJuCq/26R6HpKWykQXuSOq/21RYcbg==";
  };
  "c12@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/c12/-/c12-3.1.0.tgz";
    hash = "sha512-uWoS8OU1MEIsOv8p/5a82c3H31LsWVR5qiyXVfBNOzfffjUWtPnhAb4BYI2uG2HfGmZmFjCtui5XNWaps+iFuw==";
  };
  "chevrotain@10.5.0" = fetchurl {
    url = "https://registry.npmjs.org/chevrotain/-/chevrotain-10.5.0.tgz";
    hash = "sha512-Pkv5rBY3+CsHOYfV5g/Vs5JY9WTHHDEKOlohI2XeygaZhUeqhAlldZ8Hz9cRmxu709bvS08YzxHdTPHhffc13A==";
  };
  "chokidar@4.0.3" = fetchurl {
    url = "https://registry.npmjs.org/chokidar/-/chokidar-4.0.3.tgz";
    hash = "sha512-Qgzu8kfBvo+cA4962jnP1KkS6Dop5NS6g7R5LFYJr4b8Ub94PPQXUksCw9PvXoeXPRRddRNC5C1JQUR2SMGtnA==";
  };
  "citty@0.1.6" = fetchurl {
    url = "https://registry.npmjs.org/citty/-/citty-0.1.6.tgz";
    hash = "sha512-tskPPKEs8D2KPafUypv2gxwJP8h/OaJmC82QQGGDQcHvXX43xF2VDACcJVmZ0EuSxkpO9Kc4MlrA3q0+FG58AQ==";
  };
  "citty@0.2.1" = fetchurl {
    url = "https://registry.npmjs.org/citty/-/citty-0.2.1.tgz";
    hash = "sha512-kEV95lFBhQgtogAPlQfJJ0WGVSokvLr/UEoFPiKKOXF7pl98HfUVUD0ejsuTCld/9xH9vogSywZ5KqHzXrZpqg==";
  };
  "confbox@0.2.4" = fetchurl {
    url = "https://registry.npmjs.org/confbox/-/confbox-0.2.4.tgz";
    hash = "sha512-ysOGlgTFbN2/Y6Cg3Iye8YKulHw+R2fNXHrgSmXISQdMnomY6eNDprVdW9R5xBguEqI954+S6709UyiO7B+6OQ==";
  };
  "consola@3.4.2" = fetchurl {
    url = "https://registry.npmjs.org/consola/-/consola-3.4.2.tgz";
    hash = "sha512-5IKcdX0nnYavi6G7TtOhwkYzyjfJlatbjMjuLSfE2kYT5pMDOilZ4OvMhi637CcDICTmz3wARPoyhqyX1Y+XvA==";
  };
  "cross-spawn@7.0.6" = fetchurl {
    url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
    hash = "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
  };
  "csstype@3.2.3" = fetchurl {
    url = "https://registry.npmjs.org/csstype/-/csstype-3.2.3.tgz";
    hash = "sha512-z1HGKcYy2xA8AGQfwrn0PAy+PB7X/GSj3UVJW9qKyn43xWa+gl5nXmU4qqLMRzWVLFC8KusUX8T/0kCiOYpAIQ==";
  };
  "deepmerge-ts@7.1.5" = fetchurl {
    url = "https://registry.npmjs.org/deepmerge-ts/-/deepmerge-ts-7.1.5.tgz";
    hash = "sha512-HOJkrhaYsweh+W+e74Yn7YStZOilkoPb6fycpwNLKzSPtruFs48nYis0zy5yJz1+ktUhHxoRDJ27RQAWLIJVJw==";
  };
  "defu@6.1.4" = fetchurl {
    url = "https://registry.npmjs.org/defu/-/defu-6.1.4.tgz";
    hash = "sha512-mEQCMmwJu317oSz8CwdIOdwf3xMif1ttiM8LTufzc3g6kR+9Pe236twL8j3IYT1F7GfRgGcW6MWxzZjLIkuHIg==";
  };
  "denque@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/denque/-/denque-2.1.0.tgz";
    hash = "sha512-HVQE3AAb/pxF8fQAoiqpvg9i3evqug3hoiwakOyZAwJm+6vZehbkYXZ0l4JxS+I3QxM97v5aaRNhj8v5oBhekw==";
  };
  "destr@2.0.5" = fetchurl {
    url = "https://registry.npmjs.org/destr/-/destr-2.0.5.tgz";
    hash = "sha512-ugFTXCtDZunbzasqBxrK93Ik/DRYsO6S/fedkWEMKqt04xZ4csmnmwGDBAb07QWNaGMAmnTIemsYZCksjATwsA==";
  };
  "dotenv@16.6.1" = fetchurl {
    url = "https://registry.npmjs.org/dotenv/-/dotenv-16.6.1.tgz";
    hash = "sha512-uBq4egWHTcTt33a72vpSG0z3HnPuIl6NqYcTrKEg2azoEyl2hpW0zqlxysq2pK9HlDIHyHyakeYaYnSAwd8bow==";
  };
  "drizzle-orm@0.45.1" = fetchurl {
    url = "https://registry.npmjs.org/drizzle-orm/-/drizzle-orm-0.45.1.tgz";
    hash = "sha512-Te0FOdKIistGNPMq2jscdqngBRfBpC8uMFVwqjf6gtTVJHIQ/dosgV/CLBU2N4ZJBsXL5savCba9b0YJskKdcA==";
  };
  "effect@3.18.4" = fetchurl {
    url = "https://registry.npmjs.org/effect/-/effect-3.18.4.tgz";
    hash = "sha512-b1LXQJLe9D11wfnOKAk3PKxuqYshQ0Heez+y5pnkd3jLj1yx9QhM72zZ9uUrOQyNvrs2GZZd/3maL0ZV18YuDA==";
  };
  "empathic@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/empathic/-/empathic-2.0.0.tgz";
    hash = "sha512-i6UzDscO/XfAcNYD75CfICkmfLedpyPDdozrLMmQc5ORaQcdMoc21OnlEylMIqI7U8eniKrPMxxtj8k0vhmJhA==";
  };
  "exsolve@1.0.8" = fetchurl {
    url = "https://registry.npmjs.org/exsolve/-/exsolve-1.0.8.tgz";
    hash = "sha512-LmDxfWXwcTArk8fUEnOfSZpHOJ6zOMUJKOtFLFqJLoKJetuQG874Uc7/Kki7zFLzYybmZhp1M7+98pfMqeX8yA==";
  };
  "fast-check@3.23.2" = fetchurl {
    url = "https://registry.npmjs.org/fast-check/-/fast-check-3.23.2.tgz";
    hash = "sha512-h5+1OzzfCC3Ef7VbtKdcv7zsstUQwUDlYpUTvjeUsJAssPgLn7QzbboPtL5ro04Mq0rPOsMzl7q5hIbRs2wD1A==";
  };
  "foreground-child@3.3.1" = fetchurl {
    url = "https://registry.npmjs.org/foreground-child/-/foreground-child-3.3.1.tgz";
    hash = "sha512-gIXjKqtFuWEgzFRJA9WCQeSJLZDjgJUOMCMzxtvFq/37KojM1BFGufqsCy0r4qSQmYLsZYMeyRqzIWOMup03sw==";
  };
  "generate-function@2.3.1" = fetchurl {
    url = "https://registry.npmjs.org/generate-function/-/generate-function-2.3.1.tgz";
    hash = "sha512-eeB5GfMNeevm/GRYq20ShmsaGcmI81kIX2K9XQx5miC8KdHaC6Jm0qQ8ZNeGOi7wYB8OsdxKs+Y2oVuTFuVwKQ==";
  };
  "get-port-please@3.2.0" = fetchurl {
    url = "https://registry.npmjs.org/get-port-please/-/get-port-please-3.2.0.tgz";
    hash = "sha512-I9QVvBw5U/hw3RmWpYKRumUeaDgxTPd401x364rLmWBJcOQ753eov1eTgzDqRG9bqFIfDc7gfzcQEWrUri3o1A==";
  };
  "giget@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/giget/-/giget-2.0.0.tgz";
    hash = "sha512-L5bGsVkxJbJgdnwyuheIunkGatUF/zssUoxxjACCseZYAVbaqdh9Tsmmlkl8vYan09H7sbvKt4pS8GqKLBrEzA==";
  };
  "graceful-fs@4.2.11" = fetchurl {
    url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
    hash = "sha512-RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
  };
  "grammex@3.1.12" = fetchurl {
    url = "https://registry.npmjs.org/grammex/-/grammex-3.1.12.tgz";
    hash = "sha512-6ufJOsSA7LcQehIJNCO7HIBykfM7DXQual0Ny780/DEcJIpBlHRvcqEBWGPYd7hrXL2GJ3oJI1MIhaXjWmLQOQ==";
  };
  "graphmatch@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/graphmatch/-/graphmatch-1.1.1.tgz";
    hash = "sha512-5ykVn/EXM1hF0XCaWh05VbYvEiOL2lY1kBxZtaYsyvjp7cmWOU1XsAdfQBwClraEofXDT197lFbXOEVMHpvQOg==";
  };
  "hono@4.11.4" = fetchurl {
    url = "https://registry.npmjs.org/hono/-/hono-4.11.4.tgz";
    hash = "sha512-U7tt8JsyrxSRKspfhtLET79pU8K+tInj5QZXs1jSugO1Vq5dFj3kmZsRldo29mTBfcjDRVRXrEZ6LS63Cog9ZA==";
  };
  "hono@4.12.4" = fetchurl {
    url = "https://registry.npmjs.org/hono/-/hono-4.12.4.tgz";
    hash = "sha512-ooiZW1Xy8rQ4oELQ++otI2T9DsKpV0M6c6cO6JGx4RTfav9poFFLlet9UMXHZnoM1yG0HWGlQLswBGX3RZmHtg==";
  };
  "http-status-codes@2.3.0" = fetchurl {
    url = "https://registry.npmjs.org/http-status-codes/-/http-status-codes-2.3.0.tgz";
    hash = "sha512-RJ8XvFvpPM/Dmc5SV+dC4y5PCeOhT3x1Hq0NU3rjGeg5a/CqlhZ7uudknPwZFz4aeAXDcbAyaeP7GAo9lvngtA==";
  };
  "iconv-lite@0.7.2" = fetchurl {
    url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.7.2.tgz";
    hash = "sha512-im9DjEDQ55s9fL4EYzOAv0yMqmMBSZp6G0VvFyTMPKWxiSBHUj9NW/qqLmXUwXrrM7AvqSlTCfvqRb0cM8yYqw==";
  };
  "is-property@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
    hash = "sha512-Ks/IoX00TtClbGQr4TWXemAnktAQvYB7HzcCxDGqEZU6oCmb2INHuOoKxbtR+HFkmYWBKv/dOZtGRiAjDhj92g==";
  };
  "isexe@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
    hash = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
  };
  "jiti@2.6.1" = fetchurl {
    url = "https://registry.npmjs.org/jiti/-/jiti-2.6.1.tgz";
    hash = "sha512-ekilCSN1jwRvIbgeg/57YFh8qQDNbwDb9xT/qu2DAHbFFZUicIl4ygVaAvzveMhMVr3LnpSKTNnwt8PoOfmKhQ==";
  };
  "jose@6.1.3" = fetchurl {
    url = "https://registry.npmjs.org/jose/-/jose-6.1.3.tgz";
    hash = "sha512-0TpaTfihd4QMNwrz/ob2Bp7X04yuxJkjRGi4aKmOqwhov54i6u79oCv7T+C7lo70MKH6BesI3vscD1yb/yzKXQ==";
  };
  "kysely@0.28.11" = fetchurl {
    url = "https://registry.npmjs.org/kysely/-/kysely-0.28.11.tgz";
    hash = "sha512-zpGIFg0HuoC893rIjYX1BETkVWdDnzTzF5e0kWXJFg5lE0k1/LfNWBejrcnOFu8Q2Rfq/hTDTU7XLUM8QOrpzg==";
  };
  "lilconfig@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/lilconfig/-/lilconfig-2.1.0.tgz";
    hash = "sha512-utWOt/GHzuUxnLKxB6dk81RoOeoNeHgbrXiuGk4yyF5qlRz+iIVWu56E2fqGHFrXz0QNUhLB/8nKqvRH66JKGQ==";
  };
  "lodash@4.17.21" = fetchurl {
    url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
    hash = "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
  };
  "long@5.3.2" = fetchurl {
    url = "https://registry.npmjs.org/long/-/long-5.3.2.tgz";
    hash = "sha512-mNAgZ1GmyNhD7AuqnTG3/VQ26o760+ZYBPKjPvugO8+nLbYfX6TVpJPseBvopbdY+qpZ/lKUnmEc1LeZYS3QAA==";
  };
  "lru.min@1.1.4" = fetchurl {
    url = "https://registry.npmjs.org/lru.min/-/lru.min-1.1.4.tgz";
    hash = "sha512-DqC6n3QQ77zdFpCMASA1a3Jlb64Hv2N2DciFGkO/4L9+q/IpIAuRlKOvCXabtRW6cQf8usbmM6BE/TOPysCdIA==";
  };
  "memory-pager@1.5.0" = fetchurl {
    url = "https://registry.npmjs.org/memory-pager/-/memory-pager-1.5.0.tgz";
    hash = "sha512-ZS4Bp4r/Zoeq6+NLJpP+0Zzm0pR8whtGPf1XExKLJBAczGMnSi3It14OiNCStjQjM6NU1okjQGSxgEZN8eBYKg==";
  };
  "mongodb-connection-string-url@7.0.1" = fetchurl {
    url = "https://registry.npmjs.org/mongodb-connection-string-url/-/mongodb-connection-string-url-7.0.1.tgz";
    hash = "sha512-h0AZ9A7IDVwwHyMxmdMXKy+9oNlF0zFoahHiX3vQ8e3KFcSP3VmsmfvtRSuLPxmyv2vjIDxqty8smTgie/SNRQ==";
  };
  "mongodb@7.1.0" = fetchurl {
    url = "https://registry.npmjs.org/mongodb/-/mongodb-7.1.0.tgz";
    hash = "sha512-kMfnKunbolQYwCIyrkxNJFB4Ypy91pYqua5NargS/f8ODNSJxT03ZU3n1JqL4mCzbSih8tvmMEMLpKTT7x5gCg==";
  };
  "mysql2@3.15.3" = fetchurl {
    url = "https://registry.npmjs.org/mysql2/-/mysql2-3.15.3.tgz";
    hash = "sha512-FBrGau0IXmuqg4haEZRBfHNWB5mUARw6hNwPDXXGg0XzVJ50mr/9hb267lvpVMnhZ1FON3qNd4Xfcez1rbFwSg==";
  };
  "named-placeholders@1.1.6" = fetchurl {
    url = "https://registry.npmjs.org/named-placeholders/-/named-placeholders-1.1.6.tgz";
    hash = "sha512-Tz09sEL2EEuv5fFowm419c1+a/jSMiBjI9gHxVLrVdbUkkNUUfjsVYs9pVZu5oCon/kmRh9TfLEObFtkVxmY0w==";
  };
  "nanostores@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/nanostores/-/nanostores-1.1.1.tgz";
    hash = "sha512-EYJqS25r2iBeTtGQCHidXl1VfZ1jXM7Q04zXJOrMlxVVmD0ptxJaNux92n1mJ7c5lN3zTq12MhH/8x59nP+qmg==";
  };
  "node-fetch-native@1.6.7" = fetchurl {
    url = "https://registry.npmjs.org/node-fetch-native/-/node-fetch-native-1.6.7.tgz";
    hash = "sha512-g9yhqoedzIUm0nTnTqAQvueMPVOuIY16bqgAJJC8XOOubYFNwz6IER9qs0Gq2Xd0+CecCKFjtdDTMA4u4xG06Q==";
  };
  "nypm@0.6.5" = fetchurl {
    url = "https://registry.npmjs.org/nypm/-/nypm-0.6.5.tgz";
    hash = "sha512-K6AJy1GMVyfyMXRVB88700BJqNUkByijGJM8kEHpLdcAt+vSQAVfkWWHYzuRXHSY6xA2sNc5RjTj0p9rE2izVQ==";
  };
  "ohash@2.0.11" = fetchurl {
    url = "https://registry.npmjs.org/ohash/-/ohash-2.0.11.tgz";
    hash = "sha512-RdR9FQrFwNBNXAr4GixM8YaRZRJ5PUWbKYbE5eOsrwAjJW0q2REGcf79oYPsLyskQCZG1PLN+S/K1V00joZAoQ==";
  };
  "path-key@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
    hash = "sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
  };
  "pathe@2.0.3" = fetchurl {
    url = "https://registry.npmjs.org/pathe/-/pathe-2.0.3.tgz";
    hash = "sha512-WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
  };
  "perfect-debounce@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/perfect-debounce/-/perfect-debounce-1.0.0.tgz";
    hash = "sha512-xCy9V055GLEqoFaHoC1SoLIaLmWctgCUaBaWxDZ7/Zx4CTyX7cJQLJOok/orfjZAh9kEYpjJa4d0KcJmCbctZA==";
  };
  "pg-cloudflare@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/pg-cloudflare/-/pg-cloudflare-1.3.0.tgz";
    hash = "sha512-6lswVVSztmHiRtD6I8hw4qP/nDm1EJbKMRhf3HCYaqud7frGysPv7FYJ5noZQdhQtN2xJnimfMtvQq21pdbzyQ==";
  };
  "pg-connection-string@2.11.0" = fetchurl {
    url = "https://registry.npmjs.org/pg-connection-string/-/pg-connection-string-2.11.0.tgz";
    hash = "sha512-kecgoJwhOpxYU21rZjULrmrBJ698U2RxXofKVzOn5UDj61BPj/qMb7diYUR1nLScCDbrztQFl1TaQZT0t1EtzQ==";
  };
  "pg-int8@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/pg-int8/-/pg-int8-1.0.1.tgz";
    hash = "sha512-WCtabS6t3c8SkpDBUlb1kjOs7l66xsGdKpIPZsg4wR+B3+u9UAum2odSsF9tnvxg80h4ZxLWMy4pRjOsFIqQpw==";
  };
  "pg-pool@3.12.0" = fetchurl {
    url = "https://registry.npmjs.org/pg-pool/-/pg-pool-3.12.0.tgz";
    hash = "sha512-eIJ0DES8BLaziFHW7VgJEBPi5hg3Nyng5iKpYtj3wbcAUV9A1wLgWiY7ajf/f/oO1wfxt83phXPY8Emztg7ITg==";
  };
  "pg-protocol@1.12.0" = fetchurl {
    url = "https://registry.npmjs.org/pg-protocol/-/pg-protocol-1.12.0.tgz";
    hash = "sha512-uOANXNRACNdElMXJ0tPz6RBM0XQ61nONGAwlt8da5zs/iUOOCLBQOHSXnrC6fMsvtjxbOJrZZl5IScGv+7mpbg==";
  };
  "pg-types@2.2.0" = fetchurl {
    url = "https://registry.npmjs.org/pg-types/-/pg-types-2.2.0.tgz";
    hash = "sha512-qTAAlrEsl8s4OiEQY69wDvcMIdQN6wdz5ojQiOy6YRMuynxenON0O5oCpJI6lshc6scgAY8qvJ2On/p+CXY0GA==";
  };
  "pg@8.19.0" = fetchurl {
    url = "https://registry.npmjs.org/pg/-/pg-8.19.0.tgz";
    hash = "sha512-QIcLGi508BAHkQ3pJNptsFz5WQMlpGbuBGBaIaXsWK8mel2kQ/rThYI+DbgjUvZrIr7MiuEuc9LcChJoEZK1xQ==";
  };
  "pgpass@1.0.5" = fetchurl {
    url = "https://registry.npmjs.org/pgpass/-/pgpass-1.0.5.tgz";
    hash = "sha512-FdW9r/jQZhSeohs1Z3sI1yxFQNFvMcnmfuj4WBMUTxOrAyLMaTcE1aAMBiTlbMNaXvBCQuVi0R7hd8udDSP7ug==";
  };
  "pkg-types@2.3.0" = fetchurl {
    url = "https://registry.npmjs.org/pkg-types/-/pkg-types-2.3.0.tgz";
    hash = "sha512-SIqCzDRg0s9npO5XQ3tNZioRY1uK06lA41ynBC1YmFTmnY6FjUjVt6s4LoADmwoig1qqD0oK8h1p/8mlMx8Oig==";
  };
  "postgres-array@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/postgres-array/-/postgres-array-2.0.0.tgz";
    hash = "sha512-VpZrUqU5A69eQyW2c5CA1jtLecCsN2U/bD6VilrFDWq5+5UIEVO7nazS3TEcHf1zuPYO/sqGvUvW62g86RXZuA==";
  };
  "postgres-bytea@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/postgres-bytea/-/postgres-bytea-1.0.1.tgz";
    hash = "sha512-5+5HqXnsZPE65IJZSMkZtURARZelel2oXUEO8rH83VS/hxH5vv1uHquPg5wZs8yMAfdv971IU+kcPUczi7NVBQ==";
  };
  "postgres-date@1.0.7" = fetchurl {
    url = "https://registry.npmjs.org/postgres-date/-/postgres-date-1.0.7.tgz";
    hash = "sha512-suDmjLVQg78nMK2UZ454hAG+OAW+HQPZ6n++TNDUX+L0+uUlLywnoxJKDou51Zm+zTCjrCl0Nq6J9C5hP9vK/Q==";
  };
  "postgres-interval@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/postgres-interval/-/postgres-interval-1.2.0.tgz";
    hash = "sha512-9ZhXKM/rw350N1ovuWHbGxnGh/SNJ4cnxHiM0rxE4VN41wsg8P8zWn9hv/buK00RP4WvlOyr/RBDiptyxVbkZQ==";
  };
  "postgres@3.4.7" = fetchurl {
    url = "https://registry.npmjs.org/postgres/-/postgres-3.4.7.tgz";
    hash = "sha512-Jtc2612XINuBjIl/QTWsV5UvE8UHuNblcO3vVADSrKsrc6RqGX6lOW1cEo3CM2v0XG4Nat8nI+YM7/f26VxXLw==";
  };
  "prisma@7.4.2" = fetchurl {
    url = "https://registry.npmjs.org/prisma/-/prisma-7.4.2.tgz";
    hash = "sha512-2bP8Ruww3Q95Z2eH4Yqh4KAENRsj/SxbdknIVBfd6DmjPwmpsC4OVFMLOeHt6tM3Amh8ebjvstrUz3V/hOe1dA==";
  };
  "proper-lockfile@4.1.2" = fetchurl {
    url = "https://registry.npmjs.org/proper-lockfile/-/proper-lockfile-4.1.2.tgz";
    hash = "sha512-TjNPblN4BwAWMXU8s9AEz4JmQxnD1NNL7bNOY/AKUzyamc379FWASUhc/K1pL2noVb+XmZKLL68cjzLsiOAMaA==";
  };
  "punycode@2.3.1" = fetchurl {
    url = "https://registry.npmjs.org/punycode/-/punycode-2.3.1.tgz";
    hash = "sha512-vYt7UD1U9Wg6138shLtLOvdAu+8DsC/ilFtEVHcH+wydcSpNE20AfSOduf6MkRFahL5FY7X1oU7nKVZFtfq8Fg==";
  };
  "pure-rand@6.1.0" = fetchurl {
    url = "https://registry.npmjs.org/pure-rand/-/pure-rand-6.1.0.tgz";
    hash = "sha512-bVWawvoZoBYpp6yIoQtQXHZjmz35RSVHnUOTefl8Vcjr8snTPY1wnpSPMWekcFwbxI6gtmT7rSYPFvz71ldiOA==";
  };
  "rc9@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/rc9/-/rc9-2.1.2.tgz";
    hash = "sha512-btXCnMmRIBINM2LDZoEmOogIZU7Qe7zn4BpomSKZ/ykbLObuBdvG+mFq11DL6fjH1DRwHhrlgtYWG96bJiC7Cg==";
  };
  "react-dom@19.2.4" = fetchurl {
    url = "https://registry.npmjs.org/react-dom/-/react-dom-19.2.4.tgz";
    hash = "sha512-AXJdLo8kgMbimY95O2aKQqsz2iWi9jMgKJhRBAxECE4IFxfcazB2LmzloIoibJI3C12IlY20+KFaLv+71bUJeQ==";
  };
  "react@19.2.4" = fetchurl {
    url = "https://registry.npmjs.org/react/-/react-19.2.4.tgz";
    hash = "sha512-9nfp2hYpCwOjAN+8TZFGhtWEwgvWHXqESH8qT89AT/lWklpLON22Lc8pEtnpsZz7VmawabSU0gCjnj8aC0euHQ==";
  };
  "readdirp@4.1.2" = fetchurl {
    url = "https://registry.npmjs.org/readdirp/-/readdirp-4.1.2.tgz";
    hash = "sha512-GDhwkLfywWL2s6vEjyhri+eXmfH6j1L7JE27WhqLeYzoh/A3DBaYGEj2H/HFZCn/kMfim73FXxEJTw06WtxQwg==";
  };
  "regexp-to-ast@0.5.0" = fetchurl {
    url = "https://registry.npmjs.org/regexp-to-ast/-/regexp-to-ast-0.5.0.tgz";
    hash = "sha512-tlbJqcMHnPKI9zSrystikWKwHkBqu2a/Sgw01h3zFjvYrMxEDYHzzoMZnUrbIfpTFEsoRnnviOXNCzFiSc54Qw==";
  };
  "remeda@2.33.4" = fetchurl {
    url = "https://registry.npmjs.org/remeda/-/remeda-2.33.4.tgz";
    hash = "sha512-ygHswjlc/opg2VrtiYvUOPLjxjtdKvjGz1/plDhkG66hjNjFr1xmfrs2ClNFo/E6TyUFiwYNh53bKV26oBoMGQ==";
  };
  "retry@0.12.0" = fetchurl {
    url = "https://registry.npmjs.org/retry/-/retry-0.12.0.tgz";
    hash = "sha512-9LkiTwjUh6rT555DtE9rTX+BKByPfrMzEAtnlEtdEwr3Nkffwiihqe2bWADg+OQRjt9gl6ICdmB/ZFDCGAtSow==";
  };
  "rou3@0.7.12" = fetchurl {
    url = "https://registry.npmjs.org/rou3/-/rou3-0.7.12.tgz";
    hash = "sha512-iFE4hLDuloSWcD7mjdCDhx2bKcIsYbtOTpfH5MHHLSKMOUyjqQXTeZVa289uuwEGEKFoE/BAPbhaU4B774nceg==";
  };
  "safer-buffer@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
    hash = "sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
  };
  "scheduler@0.27.0" = fetchurl {
    url = "https://registry.npmjs.org/scheduler/-/scheduler-0.27.0.tgz";
    hash = "sha512-eNv+WrVbKu1f3vbYJT/xtiF5syA5HPIMtf9IgY/nKg0sWqzAUEvqY/xm7OcZc/qafLx/iO9FgOmeSAp4v5ti/Q==";
  };
  "seq-queue@0.0.5" = fetchurl {
    url = "https://registry.npmjs.org/seq-queue/-/seq-queue-0.0.5.tgz";
    hash = "sha512-hr3Wtp/GZIc/6DAGPDcV4/9WoZhjrkXsi5B/07QgX8tsdc6ilr7BFM6PM6rbdAX1kFSDYeZGLipIZZKyQP0O5Q==";
  };
  "set-cookie-parser@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/set-cookie-parser/-/set-cookie-parser-3.0.1.tgz";
    hash = "sha512-n7Z7dXZhJbwuAHhNzkTti6Aw9QDDjZtm3JTpTGATIdNzdQz5GuFs22w90BcvF4INfnrL5xrX3oGsuqO5Dx3A1Q==";
  };
  "shebang-command@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
    hash = "sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
  };
  "shebang-regex@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
    hash = "sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
  };
  "signal-exit@3.0.7" = fetchurl {
    url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
    hash = "sha512-wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
  };
  "signal-exit@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
    hash = "sha512-bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
  };
  "sparse-bitfield@3.0.3" = fetchurl {
    url = "https://registry.npmjs.org/sparse-bitfield/-/sparse-bitfield-3.0.3.tgz";
    hash = "sha512-kvzhi7vqKTfkh0PZU+2D2PIllw2ymqJKujUcyPMd9Y75Nv4nPbGJZXNhxsgdQab2BmlDct1YnfQCguEvHr7VsQ==";
  };
  "split2@4.2.0" = fetchurl {
    url = "https://registry.npmjs.org/split2/-/split2-4.2.0.tgz";
    hash = "sha512-UcjcJOWknrNkF6PLX83qcHM6KHgVKNkV62Y8a5uYDVv9ydGQVwAHMKqHdJje1VTWpljG0WYpCDhrCdAOYH4TWg==";
  };
  "sqlstring@2.3.3" = fetchurl {
    url = "https://registry.npmjs.org/sqlstring/-/sqlstring-2.3.3.tgz";
    hash = "sha512-qC9iz2FlN7DQl3+wjwn3802RTyjCx7sDvfQEXchwa6CWOx07/WVfh91gBmQ9fahw8snwGEWU3xGzOt4tFyHLxg==";
  };
  "std-env@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/std-env/-/std-env-3.10.0.tgz";
    hash = "sha512-5GS12FdOZNliM5mAOxFRg7Ir0pWz8MdpYm6AY6VPkGpbA7ZzmbzNcBJQ0GPvvyWgcY7QAhCgf9Uy89I03faLkg==";
  };
  "tinyexec@1.0.2" = fetchurl {
    url = "https://registry.npmjs.org/tinyexec/-/tinyexec-1.0.2.tgz";
    hash = "sha512-W/KYk+NFhkmsYpuHq5JykngiOCnxeVL8v8dFnqxSD8qEEdRfXk1SDM6JzNqcERbcGYj9tMrDQBYV9cjgnunFIg==";
  };
  "tr46@5.1.1" = fetchurl {
    url = "https://registry.npmjs.org/tr46/-/tr46-5.1.1.tgz";
    hash = "sha512-hdF5ZgjTqgAntKkklYw0R03MG2x/bSzTtkxmIRw/sTNV8YXsCJ1tfLAX23lhxhHJlEf3CRCOCGGWw3vI3GaSPw==";
  };
  "undici-types@7.18.2" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.18.2.tgz";
    hash = "sha512-AsuCzffGHJybSaRrmr5eHr81mwJU3kjw6M+uprWvCXiNeN9SOGwQ3Jn8jb8m3Z6izVgknn1R0FTCEAP2QrLY/w==";
  };
  "uuid@13.0.0" = fetchurl {
    url = "https://registry.npmjs.org/uuid/-/uuid-13.0.0.tgz";
    hash = "sha512-XQegIaBTVUjSHliKqcnFqYypAd4S+WCYt5NIeRs6w/UAry7z8Y9j5ZwRRL4kzq9U3sD6v+85er9FvkEaBpji2w==";
  };
  "valibot@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/valibot/-/valibot-1.2.0.tgz";
    hash = "sha512-mm1rxUsmOxzrwnX5arGS+U4T25RdvpPjPN4yR0u9pUBov9+zGVtO84tif1eY4r6zWxVxu3KzIyknJy3rxfRZZg==";
  };
  "webidl-conversions@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-7.0.0.tgz";
    hash = "sha512-VwddBukDzu71offAQR975unBIGqfKZpM+8ZX6ySk8nYhVoo5CYaZyzt3YBvYtRtO+aoGlqxPg/B87NGVZ/fu6g==";
  };
  "whatwg-url@14.2.0" = fetchurl {
    url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-14.2.0.tgz";
    hash = "sha512-De72GdQZzNTUBBChsXueQUnPKDkg/5A5zp7pFDuQAj5UFoENpiACU0wlCvzpAGnTkj++ihpKwKyYewn/XNUbKw==";
  };
  "which@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
    hash = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
  };
  "xtend@4.0.2" = fetchurl {
    url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
    hash = "sha512-LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
  };
  "zeptomatch@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/zeptomatch/-/zeptomatch-2.1.0.tgz";
    hash = "sha512-KiGErG2J0G82LSpniV0CtIzjlJ10E04j02VOudJsPyPwNZgGnRKQy7I1R7GMyg/QswnE4l7ohSGrQbQbjXPPDA==";
  };
  "zod@4.3.6" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.3.6.tgz";
    hash = "sha512-rftlrkhHZOcjDwkGlnUtZZkvaPHCsDATp4pGpuOOMDaTdDDXF91wuVDJoWoPsKX/3YPQ5fHuF3STjcYyKr+Qhg==";
  };
}
